image:
  tag: "sha-523afff"
replicaCount: 1
config:
  mongoHost: "mongodb.rentlora-prod.svc.cluster.local"
  mongoDbName: "rentlora_prod"
  logLevel: "INFO"
  bookingServiceUrl: "http://rentlora-booking-service:8003"

hpa:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
networkPolicy:
  enabled: true
