apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None   # Headless service — required for StatefulSet DNS
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo
      protocol: TCP
