apiVersion: v2
name: rentlora-ui
description: Helm chart for the Rentlora React UI
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: rentlora
    url: https://github.com/rentlora
