replicaCount: 1
image:
  repository: ghcr.io/rentlora/rentlora-booking-service
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8003
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
config:
  mongoHost: "mongodb"
  mongoPort: "27017"
  mongoDbName: "rentlora"
  logLevel: "INFO"
secrets:
  mongoUrl: ""


imagePullSecrets:
  - name: ghcr-secret

networkPolicy:
  enabled: false
