image:
  tag: "sha-a9b6ed5"
replicaCount: 1
config:
  mongoHost: "mongodb.rentlora-prod.svc.cluster.local"
  mongoDbName: "rentlora_prod"
  logLevel: "INFO"
hpa:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
networkPolicy:
  enabled: true
