image:
  tag: "sha-3bb1b44"
replicaCount: 2
config:
  mongoHost: "mongodb.rentlora-prod.svc.cluster.local"
  mongoDbName: "rentlora_prod"
  logLevel: "INFO"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
