apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-{{ .Values.environment }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.nfsServer }}
  share: /var/nfs/{{ .Values.environment }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
