---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    .dockerconfigjson: AgA+yOQp02ddRvvNVDdC+NL8DbnzBODv0DJGONJctFyoE6x5rGCCT7FXP5BAM4TMRj6Wtm65eASQSeC+oQo8r1qlhOJJzDSGlPL6GFaNY7ergsganXxHEkvY/9nZ2ppTAQi+T/idZH9F5upBPDaDhLqckmrxYStHjHYh/QUNBl5iI1bBzVGHY3Pg5cKXIQv33S9CwxwEVDLeLJCcnSlJmpE1HXABUd13Kr2VJrvRNtGNtZ+u/KI3rukbsttdaDyhS/oiXNfkvIEg4A3auJiZrfD/cFR6+/ZaZrGJNo5pzw6Tc2qkMnsYeQjBccdtH6DW129ksSnPhEa2XEAjCLmOLDD2SoN8lrn9elIRkxKvTK28UQUdEUV4RZAuHjSSnRUDPjH5zzgEdOMpayhELb75JbTEV8fgqFhE8/BHaPLipsWhjpgDa0fkH2kpAbhRMvj0+2mKzhEgcfA6aEAn9hMHhuQnGGiWeQ6YCxbqxYcoxEEo5yvrpVd7Y7J0uBel2KItd2jlaMvKFtLQ6gflds/Fp4A3CC7I1DvAhW1U5maFsai3ELhytWCxDgHuk6cydg7dHrQxxksP6lc9+Mo/wAtfqB4Jq5RL7f/ESDGWq2GVzp5/nfBxnV0b14w5UxNBzOYAd1X05cmhJatoDnN3JuJ/2Pm4+iYeYS/oU859RrC+IkLzWFsgrUasw6+Q32ESKD3HZ6FdF+UvXWdbdz5lYUH8cS9t2GxlTKRx7Bvnc5OZoMDQ5JNBsdgmWXmMXw7NbQBD9frvN/M7IL4Zm/HwU6M9mBKvriMLNsuMJZF4KTME3LSph6SvasnGScmpGW5gg1BaVBeX27zWsmIg9ReVWNvuyzmmv2HIwV+T3UKazezoJv8yXm6zhyEBfnHL2sjHJ4JEyioFOI395Qz5bel63dpP0WoS9OMMsT+SOYeTGzDnLM3Pvfc=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: rentlora-prod
    type: kubernetes.io/dockerconfigjson
