apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rentlora/rentlora-helm.git
    targetRevision: HEAD
    path: loki
    helm:
      releaseName: loki
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
