---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-root-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    mongoRootPassword: AgCcpHK5PTBlJqJuFm5j9ABNGPrnIEeQnZUMzLMNW0iZDCzD8KRPB0HZB7ANkKgdpbphbixsFBLBmVCHUFiSzoFU+bwhfj2SuYSECu6zN6zGX2OBAKz25Lzsbp5GtNdWskjOR4lldW5Tko6pPM+TybaCV/ihi+fROWqnrAuu982byCVQlsBhnj6T+cU+nf7YUrC4M5N+pjqCvlPUdSWbERZ9JlHf6lJstHjiRVbpjpUUpSZ4UIw4ParssO7QHhhrvpbEjoh45ZL875yl9a7f91e0G0/93GN/xiii62A5ulSCz4G8aY4DVg2hcRQN43XBQrlsUaz3iJCi8DbWcGAuJXmt15Itp0la7Pt9wXaOOrK4XaYACFDkZ61Iwlwh4YjdGJV18cLnUEX+YE6DYIr8AVfKKt/+5+xQcQNYYorYvHEceFN16Gazm0NsADhC5HsWLzOw4h9X5Gl83dRDHQeL+cosHKYEQZtj1jGfBrxO97WFp84qGbVSqo3VloXX3yU0YCQFOWR54P6kgs0A3bBHJuCNb3ymq1ZS88lMxidPBxsCGrzZ2pNzB21f1wZsy4nr6PwTnr8xbC+hTb97vi6amLShr1uNWTGVJU5svUs8UcJKSX3OCRq6QPxcksUAN2q8SH68tGSgmJspWceZuPEp3Jnv7AwFuGX8koVXSvybRm3kGuxBRveEQzKB5UEe1BpK1EOA27ppDrBb2w==
    mongoRootUsername: AgBy+ybMcnQ6m01gsdzIDCCHhSfLIFiXix5kr3HT86hOz9Egfp3Mr7tyYUJOSLwrP3+2dC6ISspNkOdR0qhllnYsF7DqnCoMPoT3h61t4onwOx7gFOYmtmUwMOoA1mbGWLEmzlbZH2LZ/dRWwAa3YVdNa6PFz8MeWOGzg0oWWjJ4VP686TmkCvmN8zLWO07X4tkPHBMvLWKlMnJ6c0+hIKCcjLBvrBzJtiI9KX/KaWDcBvcnVNJtLW6lRch7che9awcyXRZHg+2ss+jQbj8voFaWhhXiqKaACgVGe3rVVl8/zvtUO/MAO5+qK6YYQnZnKPkSG18ox7CfbgMnDoaVwrlpcQy9McpvzfZGLBUUi66Q9SyVodQXKiO+5f/awUKjsGgtq1zvNd/rny+H1t4i1Gfv2S0yhQALG7h0Btz23LHdxVytAPLZru1ZaNKY0M678r6NKmCc+ezCz2J+xKibAydOIYCMkX7Y//hJXfjidk4djUYU9Q88ijQg6o4iPNAHCTSNAD0EVY9yN4vDBxG6oNzBJQIggKP25lgTsRoKAmcLavQNzxA5E1uVpIBof/EQqO8I4DEXNEvOngUSU0UyYx8UKOvTmcm0fRJY78hnTQY0Hr7Isl0re/JMS4dhXzwji0IiluXW+WXKB5mRqVEXzutGzWy109nmzcAIcrnFWpOyxpjX0sFWAy0EtaEX/5S2JtO8X8q+hB0e8Q==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-root-secret
      namespace: rentlora-prod