---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgCSXFbX/OQlcvHbgYaV5BjokOrR/mEBSnSdzoR8RiVUFHC+GGEYsW5KoJE03x0A2YFlYz9+sW2WWiHgpEHRvhRdcXCJLI4eLgLX3GwD0XOpPyBY49qgGgXeSXsZMDdQ9T4xeshMuA6dkHsqedE9bWjbkcut3dzLmGauppHvokDOZPth7m6zhOYk+DL9bmWBz1kADLi96lwskXKQIsQrSTP04Rbx8wDrSN4yAKWrHHvo+ebB5KUpMsVPvrQ7ZjfbiCPYUUCIXOEBAz5lQhvlWmjHM5FoHABnLdMV2powLsO7GNStyudCRsPV2vsX32PbT9zFun5Eo4SCLTnGcDRjAevYit4mjm5jlUoeLZsyPQP4AenymI2scmKD31AHOGLiUr8Rbs2TVXIl2WlnmvimnULJ8tcmoMEIyaYHzYUAeDFPWNubeTubM6aa2KLyYjmuJ8BmEjUrs1pehxrij+32Oi2R8xzvU3xFmPE6Wt/LarA8uODDQG7oV2r+CBYXdXAgdhzdyrZkFx5kPn1WRwt8PtTPHhYjX4phHACqta5baNH0BSSrkX1eiWGquu3b0QGLU4BHVAuKhrsoBPwISdzWp/qiS5var6TZB1KryUFkR3DsdowsCdV0HaIwK8qbV6vcPc94JO4MSLMpPf0xHTG8XXjyx8mVG+JqYszE/DVxRzHAh59ZGNV2k9FLGqomydk3qBpeWmKR8uLrYFag0NdVjSYWeRV7
    MONGO_ROOT_USERNAME: AgB56F7v0MrhhwrYghtpklV4bv9N+TU2u1XxI0fnidzotKsRMCzI/SmjE7bmb3+0DTKPZSy4F9ui+mhlDOcgmAaKg/8dqs9PLnR+fepO5KyYqJxtUKvv0MRMis2mz4LwjFNzP6tTXRwVshwUcOmvXF3kqGsfaZuTykVRz5sO+W6eU8BtciB2UkGJ5GGvsMknpsNDRkESppBTtTtcJvfUoNT+CU4nl2zd/63Yx0WumOxHIpBI1LLe6WOTFuNkAMEcB1LtJzY86K87PHfGmFQHHW3XroUE+PwV0Jh7l7TMUjkL2YIE3loAFZSprkaDs24gQ6KwxNLIjmpAy/pBo6UiBsj9N/CBSKK0ymkfUJ7xOhqoAByrEZHSKHkZyHYC9ufhYtL96wiw8g8wz5xx81u8/gUfhSEB6cegdUGI7CbljIaG1kug0CBGijY07vefzMQ988at37IBcGKFA49FshZNPm9DaXLzCqGfTZjTffhc8egWgw/HhkgK15PMj9Olod+HCpZrv4oQaxbhgkERfwY5niyHsRFdHKL3nhqhteevFhcNHUzl/iLJZEJSCDfFpIXWkDtiJVpeLzW033oAUQbDCa+ytyIp8i3T9rkmfbLE+vaiDU4fX/YGtkXvyx9oiET0I2RhcAyV3+34OhXZ3cE7XiYsl+fShf/P7RyiuThdPPtooATkzyML3WhwWaE8RCrgcjv6k3VCjrdwoZ3VUUmHvw==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: rentlora-prod