---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgA96ZqdezLSq/xxS0BzCNx0MzAF+kwIA3Olfy9vgiTf7pJlxO2cQI4vTR8isfqL/cHI0npH9caRgR0x0Te4bjU/5w2xMm9OfBjofE/Oi5XrfSetbS9E5MTJar67+rtr+S59ys+d+HNhKL6p+wmVuhiXi1Ay4d9P168jdkLoveigxkqqWltTzC2BY1IT7oVJjqW1BwjWjDWQZ4qh63WKEyHSUtPAMQkOcpF2Fe5/Iq0RHSJn4Jrit06moybOSMFl/od3CWPKPjDrv6rwpojhSzVrEK2gzTO/2tDVQvfM2Vd+tsflD2wHm15EDbr7mRlEHn9rBH+H1XbduAfJ4KZLT6U2CwQ05PqLJEHgSvBXZ/aQCh9Oc9TfScAouDBGoO6/ABTxi8AtKNwIzsWcBRo/TtLvHIvTHkYpum5fQyJ4Cg/McbcQu1ZiW07veOwFicbsX9u6vJmC/TT+m/O+yp4kSbCuwSR8Yl6wmVu5YzkI2atPE0N8ejH7zCkPRGw4ZSmTqfske7QgOJXCngzCcDeWzk66CwJRcHA1+ji00P+iQTWKbTQ7JGj5Lv80RH0zHZj3j6qvF0/eA0mY3AJ3K2Q4DSkT5+fdqziBEcPx88q3MZP1cQJcrFjlNl8Qjiq7RsZXbCBJm2KuLAl51UiNPnqJ4hsRqCqw/i56AdR20+r5ATcGi7jJ1n6bP04kxoSUp75sibNco+agPVLuzjltZqxJw7922R9J
    MONGO_ROOT_USERNAME: AgAwSqFXdchIjB9EoJCdHQo2ws6Za91FMUsNLItHTwGVoMvw8hBagAtzISth1RLc07XONWLWfYi9u3VjFuhG1XTn8uIxhln8z6rHhIxQ6w89GE1kG/5Bpr2k++EvU3qwTYwZNyK18W895B+UnOfoUZgow/nlZxtVs7nx6F0DdOVt5r+PHCLp1EIWE9EVSpIMDon15B2TT7RQnm3CdbGuVF07srB8wm7XtCQtPcbTQ7fN+aichUR1FRisRZzJAjtX1C8WyE5WeHLF5MqH5rsXFO0uIVWQ+b9LxfFUUaBxhaKCKZvDfU0Rp88mrTKe6vyJ3vfTz4Oth5Lbyqsyh0fylxJRn5jtoYhignMRKWK5RXNGoVW+JrRmt7yYCdyLiJCHTrLIoK9y/3KeGykQJvEMNnn5aYJJGTg1+DDPwhLDgaPIjR0IosAwIyMwVgkleBO8FMD+zCxNk3s3PW/qb0t6bMpMcajJR2Hy4YuFbZBuerojKAkgMW212LjSayk9stgEh0ScGZcqpoecgw5178F/JAhbTE8Ia0j5rXZgHtCWY/9hOxAsRA7I8Z1i0/epobIHEblhxuIrHAoOp9d4lRpdY0l3EsdQD1wQ3lktXRu1f2ragzfwSfuSj0jW/Fbkyk7V6KoAJnj5XXKRM85f31QpmdkG8O0Rjxe9lc+SSAg0fDN4JqxdhCEMjyAIiPa+t2kwykZ7i+XeiNLxKnaZFmwxWw==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: rentlora-prod