---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-mongo-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    MONGO_URI: AgCOokFs4WLk2Zcu7Xe/HMuKyN9Tb5mcMzIHBbYxRq1AX8fLPR9z0ZwgcWfOwepbWq2yEc/okRehxSjqaZhhHQLpx8w2YcJjNEd0SanatxrzEUa+guEoQqcJCLQYGINV5BL6BjZ7n6A2fBDV92qj0fP1zFk4+Pp4CqhX8YCi6yH6z6VneVi3RZSGAzfN3lxdRvqTsyi/oWDTAiW4rBmgpZPu5+fsBujhyfJvvVr6SX86iv01EV0zZ/H/Kei8tfjHc+xW0a+UtdBk6ai/Ouzh1kqo1nSnob7k5gawS2xdRvAzB+fTCVZQ3RTW0v8V9jVusL88kC0yP/17/xstXNVUe7joMTUaOHCzC8WC8KzjinbD3yBaTh7341NlCdF79lLKX5ZoDMkZRiFdP1DBd/4Z2m2YtN5QcWmKlMHNtWjZtSa6LGRZxpjdjn2Ze7kkZVTT9/bnLBIajNkuUlnc2a69TzXj/VgbwVpPRiX4Vub9JGP89Z3uOtVDY6weFbNksb69p4ITMSF5AuZzQ/NYOziPl5k8AGnB7s0t9JDtBU1IwxdJK+O24kmfRO+oDmBjJMczswzlGVpko0L1mA5LSZ8YvQNW96RJXfBGgJFB0qe0bIc9fEuXKLSkVD8c0IjOzphnO0oayu5CJIGamZHYX/Q1/AR5TTMAfEvxtcrZqs+hHDU5DD03C8cnCmcT1g6FpkzzkbO5t38749VASRjjeV6HUGt+VsItVmYdiau1Ml8/Wd7nayinmVCvzxubFwZ/hL/dXFo64d+UpdVzFa4aHBJLpIqjXTP/UK2Q6mT+3WyWz9kV5k0t+cwFZwHUJdQM7l7F17oT4TFDAXQ7RnI7iBrLqwJjODR2eA==
  template:
    metadata:
      creationTimestamp: null
      name: shared-mongo-secret
      namespace: rentlora-prod