---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-mongo-secret
  namespace: rentlora-prod
spec:
  encryptedData:
    MONGO_URI: AgASgDOUVFnuIiC+hZli/8jeOTffeD063PB0YShb7qMEfYf2GjVCp6chgr8FbpBH+Jd1dpOVikWScfBlp6vRoclYMIfdLHvPql6BYZg5NqpcjYoKSw26ySOMbBAYV5g5Oek+/rTfrV+YfDYzINcCmy5Rkzcafb39EQ5U1i+/lfYLW5SAbKhAl8loy/5w2vYze8In6eh5wD2HgFP64Ld4z20RMfCuqopA8dGXbvVLTmiG0tFGtvFN9O8dayq4fpUjBs9USp07cLTCpRvJ/kXhSLW4Wuzy0gmGqCWztY2h8msayKF4mPGHS3+ZEgDh3uJJ6U2uObF0fLrP4UP+l2CUZFSn9qWz86OTmjR3A4lo8OVkykZb6kqciAUc5Momm1UNzzfdtcbUa6aF1+dx2geXYtkJjy2lUX5rGblrj5hiTN/mcnA0KVVNow+5jA/raqERhI9pKtoMQmSzHitz5w7AXYb6fa7F/iXOS0F30UduK0b9SyZd6gxHu1gzRZWzbDXDLFrZpoV1Yw+nP7dMnaAhL37gV26ZOf90O4EfY09kLTN0IFfFf/m02ZtMYukl5pSE+j+2yOCfYNQAv+UFWC+8bxuatOYJ037NL0q0kLwsgEPmzVY6i6/1E4SuCs/Jh23oDZSkP5c/XBsz9Hq6akA8nWTVa/Iklmvyg02XWqxj+xy8iqsk4QgagokxvdglzBW0znDGiA9N47c8S+LTX5TngLHDJZmyVTcEBVv0AC0eOWln+xI3dSpKfQQ83a4tQ14yEepYvgya+zZaT85F9tJlwD6q0UyrWXgoHfq+8HAf/xJ1hgGh5PCdfOoQby+lSkcJyyn+oXbpoqlv5w==
  template:
    metadata:
      creationTimestamp: null
      name: shared-mongo-secret
      namespace: rentlora-prod