---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: rentlora-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCNXh3BtFQBIxXZ2KWMLm+FDhX0OlSHXRu/fOvY/AH8OKrBDHkU0yQJZa0LGkAYah7dbHNy/3skuCFf6lEZJibBslMDstX02GoGC5/KNSgWe+40801cuh2PyycBsWFNDilakwKH3S3NUUlTBiHuHN2QllMjRaVrNl4fprtyos8FODJq0OE74bxvHHdLURumTv7fvXKnQn/SvOMq7MNXdFpdY7OxH/UW6ISSa+gAjd1BqAoAW7Q16DtFZ6cepRHvA2Nd3u+LvbDK7+e3L5KNpHCh+wA2WFgxxr2LdYiMR8wDnFrCPUiqRAFFwvvOSPW2fjNE5jmsFrYyQanFY1uX66q6LUbeTlsNtODNnhOnHfeFAn2dKQFNqj7y/4xZgVGBv4ntdurKPh3sEL1JWdQsQfayJ0PwX4CZNgU8mzOX+0r97XdPwsQzC08YzJl6fVIC6EOI6nMSN8u5zyqijBZUsFbj/TxcLqUokSB/GQDbYEa6DuP7QWQLy8d+FbAvHuT9JWWZaMF4AYHIT49uJjf8W33l7MLfnDjTkr9iFzIjKJ0m3jtsL3hc2fo+ZrqZlGUPQbsR2jPV+d24qsNIadoXuTJoFMS0sl6boeQm6gfUe1y1sEOCs9zxCrD+vbSnEa/LWFJrBSppAbMDmRBpsWELL0I1j4bbGScO7bqdNfR7i/Gn1P3Sp0CEcEaarXrclqPNQKwuMpqnopiGsiZR4LXcbyfB6nTooFy0Zhug1+qNI7nyAPYHWxkB/zAMWt0Pu/Lw++TG7Aqo1boWgkDhq/42HLx4U0QYFTvyq3TpMKXxxUxojmXaFLTDZ25zrsZ7GvYRv1An9BnRID7KLeZPQgz+659MnsyhGWvgRXVMxQnLUAaT5QbIfkMdC7mPEXULZsehcFVvAQHgIC/YvFw90/Dgx8GR6JGG6HibcBspu64UyQILs7M=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: rentlora-dev
    type: kubernetes.io/dockerconfigjson