---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-root-secret
  namespace: rentlora-dev
spec:
  encryptedData:
    mongoRootPassword: AgAHBBunvnNroKgJNpZv0J2Zisi1EkAgX2+HNgPHncNUeW1S//uXgjJ+sWZaWKxfp5REUmIx9Cs/drMSOM1Ju/cqPrXI9Z3Upmz5n4WBjYWfPuhLWciVo7zORsgLVzOoYavzQrvEgk5SQv9AiJpFHHm2f73eDSxEa+D6PJRleWLKsiYal8kX+MmPJ+YEJ6ukeFauH5KDQuUgoASb+8vbBWAwntUEv+8Fjc/kOl/AW8sXqlmpUiX0k/TzdW4r1QBuPaa/aXgM58dMopVRNJjSJ2JJnTLPKX4uzQnf93vdYNic3dUwBQoGSUrpxDX52jXqLwGIgfBkcIN2RKE8ijzj9a6fTwUym9vqWidxeg/2+dAeCvguyI49k22YEgBn2arVQinMbLij0vve40yGlQ4t+1LaTCVkwAkLWNlgyaJQwJiV25XDMMxVyxzhAqshqZgDV/ViscdeGsUJxoqD8Bv9NNTjjejSunQ3K3gcg/9H/dnKyVz8Fzb1VwDgJdUs0Dys+03o5av6bHgqLdlJS5gFH8kcnqVaWRYkVtwrufFv6TMrj3/GBI+gf9J4VbfbgTGQyMeTZR+5+Ejg/USW2wH1hXYvSiyy1RArmGv9lJiNUsjccNi6AaBUZVDA7nl4w7RW/KN+oB9Gk7dBlP0edkt0C+chbxtb7+5i9zIcDslFIG3lqOX+lljHUz01WprFOmN2UKvPgUPDDOWSGw==
    mongoRootUsername: AgA5SBKCB/1Foujg3ImqWkleojbbIDO4N5UjfaFvJ0tL3ordKGfbmmVoRnSMz6rXQeOffHB1yFDyBtTN6UPioSbkRwoFRiZYo2cG5R2O9aJ40hiXwwNBe6Jl1wVjU1PxaBMu/oOvfvudWjBMPckl2Gze6LDd8VNsh66cpi6/XKUP2qWztYYwM3QfR5Dfqufxs1YUwyR4VWp4KHH0mEn4gnFn0fcBZnbEhs2HXTK4QVcKkBF+HFTqpdWSV9xYGePdBXUYECwRE36mXbqqerlNqPOo52pm5U8ARO7P9EwEqIMLuIkgDe+tKaTWP0uT1YU7BJLJjJCPD1c7CXhxThcbi7SX/1fmpVkJhEWzaUSM7+LrxhgHYQLCFoJ+xJFFzWqQIrzQ3D85rzghjpzn7eRBPUxlEEv6RWM1WN3k3+/yq8wXIySRIQ8CwQJ7sxkROK1WSGTH+CBdi34v7nZLHrQ/grywZ0NEUtDml3vBUdNyq+qIc2lpM5SGk8SnXtWLStzpqDTCMQjobzwWrO3Op03V8wpeJMKBadSpeISkQRjJs9q8K/V1Zdk7t5iAMEEnkrFKCq5EDrp0ZuMQeSRebX0hozi4zeIVCjTL0E5+lw5LnTrPTRZkyFHvpAsuUbkygoUeAtDlVDLR39MgRUrkxe7hryO6zYiEPngyTAVSpVDWGL2U2YKom0d8zXitBrmi1+QFUth4PLxAguYVUA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-root-secret
      namespace: rentlora-dev