apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: rentlora-dev
spec:
  encryptedData:
    MONGO_ROOT_PASSWORD: AgCt7lZK1qh7FP5ojnZgUve24624vY+y6s20JRAm8dMqS4Znh/DCSoS9uImvH01PbSowPbYEsGM7mTvJBbgHSFF3tVyuCYJnGeI/lM5Wdb0Q+NmjKFi0VHzNc6SLQ530rSJ/je02/7dfPaq/aLUs60Pf/vf95+NaWFg2KOWKvSXmTTt/je1UEEY+X8EXaRsd9F7bypTA2udKJRcYOCpmqU0xi7vOk0vFXIcX1MjIUWw5vOvqUNcBii+MQfXKWBlS1CVZ+zHatS7xnsHOl6ZlGKOGr5Yoas2UBtabyae9PUmXyxggaGCQT2bugv9hGapp2hLA+Q5+FZO3czy0Ds4e4GMlzrfoAh/CvoYk6FBXJ9X44F5ohIri9JVsjvd/fKnGwFZppBlOOIAD0KoOXJ+1dZrumBtAjLtK3sdTkRjcEB94kvC8HpIu+8uVUsW2gO6/+KSZ1yGQIRjja+dS10ts9TK7gs/XYE6UlVu3TA4CodOimeZg0btNrkmyvc665HycakHCmO57f2vn+eGurTKoJXAXGucDNGRoS953XoJK8eNK8sAhRL/1r4cVqIaeYwrd1ZPz9LgF8FWmF5qb/dy7u9cbFXeE5T3EyGTS2/VRHLot9iMfrWI8wV8v/Ymzk7kTUip/mYSN6ZmGB1AdjkTX5wHW6ROX8954b9jfyzAzAnGeikXRZtC+HXZ6bhtNqe0U13wiDpsxOGBtDKfzW+YAVelNpMpT
    MONGO_ROOT_USERNAME: AgCvePa60paPYzY/29NzmwAEgXMk7Twgk5LYtLPtVCWOl+SvvcP9bO5tE+X52e2mKTBUkuH7LlnNUeaGiu0LziHwqZnq2C5SPtGPGTXWwUFNWaRN2FzQNRt3erTvAj9tf1cpo851vq0T31Moo+lSoFxu66SE7T93++VETy/XyFU/5S71P3TvZOSTOccyAQRyWosKFf9JPjEH5gtHL71RjZJzpP7DS8hClZVc8xANwyTiPithAJuqkZ5oD/Is4Jx+rXycZvXq5bxa+q+/iReMcBxp0jPRxCYMnortoAPp53WLliqKP5iW99D+F6n+BZ525ppRPxOOqBseDyw3ZbJup7dQ6fccOiZuyxP3Yxna9V243CJpRTBt/rq+sEyV4S2TpPJqzYuff2g2FBHiMocCkg7ckau7LtaAy2wv85jzv/7eZnHjgkr0UFgZJtlp/4bLxwJwOalZqFvNAalseqxYMqKSotfgwwlJ/69ZImBG6zvxH3hX09AH6TpsB8ewtkaYejPryr0lWGyeezcHSDYjPxiVwnxT/4at3VpoN/nc1L5QPcj2HCXwQKzPbgeeezwEU80oBPmPJn+GCdoKdJPHGwKfpyoQjXga4HUq6m6zfQYqTMs6TWU+Lkk6VHfDydK+XpzFT/lpedxIFUpalQsBuGPiYoJA0ixLvEyqxnWRv3XkqtlJXbYFCw1ArCyE5VtrAmYVq2nT8qMV4v5s4T+N2g==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: rentlora-dev