apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rentlora-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rentlora/rentlora-helm.git
    targetRevision: HEAD
    path: rentlora-ui
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rentlora-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
