---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-mongo-secret
  namespace: rentlora-dev
spec:
  encryptedData:
    MONGO_URI: AgBGvL/XXGupykwRLzRvN4Ct0+XicQC5pdaWPOE25RTv6Ldb0hsb1VWyizzKxEttJN/MqgPq0EDCDlGRqLAKacxetXegxn9ejejrX5AisrMKNudo+svDx73j8AQyfWY0alSsvyLxjSzKo9YlML1yjsX+KYVaVYtQHh5YZQMRrGWXnjrIK1bWLLvF8KzXkPguQmLWK7wGh49zdddeNTgaEOUycyiysRv5HIq4JcYygBfb/+YTyVvOwY5EjcB3ruDrth0cSzKFO8fJEgnS+j46SmyAt9EfQ75JTM8UsvbyOEqYzLkVkaGv9vEcGhkmBV16Qy62BXbwSOfC+lvqGPkp/v5GDaZUkrWHljvLOH0HSloi4/lyiB6TYbZq8yY4QCNygyDMMypc8e0P92F9MjLmke2WSPQrK2sxihfxm72VdaqfRzcsq0J2Kj7rsDKLK9afDJNIXZjgsnoDYhmXdrEg1F+72pxfkyRQyIsUXCOkiaeumN/fIqCc3ZGFxFPrmaZbmjylRZd7t7704uUmjygLF0KuBsVjwqP34yUw9WBMD/lQsF5ZPAvhIN8SChXSZc5k2IpFMXeGO5paXu4ffOdN4hEVw4RdAaqOroW1rRKFrQTSS2OdgTD6Pr4g0Dyd4Nn5ZNgI2R1mtUKwrwNet5SO4SAuf9JkB5HnV0ew/JTZO6UYHt+RlXXZOUeO/GZ9FGIhy4QsJaVD8OcVWb5ZNtHrHhfP9RPSE1MPppkHIkYZSp/2JTE8DRgdMd1Xi5wgJ+CrRPaDhAarRXHQk25RdmLcZ9jfyXLMFTesV/8d7QgmUIW5gcdA6zq//awmZWnKTHxPjIS8AniKXpk=
  template:
    metadata:
      creationTimestamp: null
      name: shared-mongo-secret
      namespace: rentlora-dev