---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: shared-mongo-secret
  namespace: rentlora-dev
spec:
  encryptedData:
    MONGO_URI: AgAYsJ+obrK2+uhuSMN+tqm4HTntOvHhaiFEWDZaCFVxsV3GxX+FRwspiqWr8N8WBhCcvuX1CDcYsQvtfian6+CyVAE3Ti/ljQwpB4oE1SksYf1numQ37iCOcqulem6hYhBTyfXXeCDLqcEVJTLGw9y7LouzcHclfV+nV6D915jqXwUvrn0F9kLVTXiQHNjJSWD59yzbvnZZjiNqQ8O3t8PyZPaZYfd+I/K1EMdrm60YlGBe6s495WCzp8MiRJsTGJg4O8EqdYqTO6TBTzl6rlTixEPFqrv27gCT37GnZERmSGZQhTWW8EzhsVEVqom1yhyT6mDCiEg+U6wbHJtc9niHY4+gZsnEs7q+CHHytidj2aOzC7tIqwQZAT9cjF6DnzkpG3xYA8G4/Gndu/dr37AJ8kaFf2K0C8TnZjEOjwMrglNlrhDTrcqmTYciKaA7mPbM1eseLcSh1im3fqvdGAyFWC3lPnEfOWqKElbXxmWlTyTwITv3EftcjRpvse3T6J9wZfxFUmhfYZUdIchtraNPjDr2+qSuidjruVXDGolulJjrDJJ3OULXEdyBLJiz99fH6tdzkuJC9GhrJIKk8PScPq1QMgVRi0Htsb/zj3PjRPk/CA93RAeKiEwNK2vVeuWQU+yV+HVPdxwCfDLPkINXsyRWm84ka8GnHe3AikdDPm+toJNN+A8d6bI+DNDd/vXwPGajQE6BJaIbMlAXHJzcPgB4zGJJh0RCZntvjcyDA9L8B9c9MH9Le0+I+hYVn0Ktl7LlB+14qkEPhjG/n4T5c4CRgNbDdC9pZeOWni+Gb6Xb7PDe01tLnw5xoRhVN5WBQMNSdyAW//hCFXqm7z+C757e
  template:
    metadata:
      creationTimestamp: null
      name: shared-mongo-secret
      namespace: rentlora-dev