apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: rentlora-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      port: {{ .Values.gateway.httpPort }}
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              shared-gateway: "true"

